#my.cnf
server_id: 1
relay_log: /var/lib/mysql/node1-relay-bin
relay_log_index: /var/lib/mysql/node1-relay-bin.index
log_bin: /var/lib/mysql/node1-bin
default_authentication_plugin: mysql_native_password

#keepalived
script: /etc/keepalived/mysqltest.sh
interval: 2
weight: 2
state: MASTER
interface: enp0s8
virtual_router_id: 51
priority: 255
advert_int: 1
virtual_ipaddres: 192.168.56.150/24

#mysqltest.sh
mysql_host: localhost
mysql_port: 3306
mysql_username: root
mysql_password: Secret-4-root