- name: Creates directory
  file:
    path: /home/future/webserver
    state: directory

- name: Copy file to directory webserver
  copy:
    src: /home/future/future5-phase-one/docker/webserver/
    dest: /home/future/webserver/

- name: Change permission for docker-entrypoint.sh
  file:
    path: /home/future/webserver/wordpress/docker-entrypoint.sh
    mode: 0755

- name: Build images and run containers using docker compose
  shell:
    chdir: /home/future/webserver/
    cmd: docker-compose up -d
