- name: Creates directory
  file:
    path: /home/future/haproxy
    state: directory

- name: Copy file to directory haproxy
  copy:
    src: /home/future/future5-phase-one/docker/haproxy/
    dest: /home/future/haproxy/

- name: Change permission for docker-entrypoint.sh
  file:
    path: /home/future/haproxy/docker-entrypoint.sh
    mode: 0755

- name: Change permission for default.conf
  file:
    path: /home/future/haproxy/default.conf
    mode: 0755

- name: Change permission for run_container.sh
  file:
    path: /home/future/haproxy/run_container.sh
    mode: 0755

- name: Build haproxy docker image
  shell:
    chdir: /home/future/haproxy/
    cmd: docker build -t my-haproxy .

- name: Run haproxy container
  shell:
    chdir: /home/future/haproxy/
    cmd: bash run_container.sh
