- name: Creates directory
  file:
    path: "{{ dir_path }}"
    state: directory

- name: Copy file mysql for create user
  template:
    src: create_user.sh.j2
    dest: "{{ dir_path }}/create_user.sh" 
    mode: 0755

- name: Execute the script mysql
  command: bash {{ dir_path }}/create_user.sh
