- name: Creates directory
  file:
    path: /home/future/mysql/
    state: directory

- name: Copy file mysql for create user
  template:
    src: create_user.sh.j2
    dest: /home/future/mysql/

- name: Change permission for create_user.sh
  file:
    path: /home/future/mysql/create_user.sh.j2
    mode: 0755

- name: Execute the script mysql
  command: bash /home/future/mysql/create_user.sh.j2
