- name: Config file my.cnf MySQL Server Master Node 1
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mysqld

- name: Setting firewalld
  firewalld:
    rich_rule: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
    zone: public
  with_items:
    - 'rule family="ipv4" source address="192.168.56.141" port protocol="tcp" port="3306" accept'
    - 'rule family="ipv4" source address="192.168.56.142" port protocol="tcp" port="3306" accept'
    - 'rule family="ipv4" source address="192.168.56.144" port protocol="tcp" port="3306" accept'
  notify:
    - reload firewalld


