version: '3.7'

services:
  wordpress:
    image: wordpress:5.7-fpm-alpine   
    container_name: wordpress-container
    restart: always
    environment:
      - WORDPRESS_DB_HOST=192.168.56.150:3306
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wordpress123
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wp-vol:/var/www/html
    networks:
      - app-network
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./nginx
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./wp-vol:/var/www/html
    networks:
     - app-network

networks: 
  app-network:
    driver: bridge
