- name: Install MySQL server
  hosts: db
  remote_user: future
  become: yes
  roles:
    - mysql_install

- name: Install keepalived and copy config file for MySQL Master 1
  hosts: mysqlmaster
  remote_user: future
  become: yes
  roles:
    - mysql_master

- name: Install keepalived and copy config file for MySQL Master 2
  hosts: mysqlslave
  remote_user: future
  become: yes
  roles:
    - mysql_slave
